server:
  port: 8087
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: admin
    password: nimda
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: terue
    properties:
      hibernate:
        show_sql: true
